### PR TITLE
feat: test cases specification generator

### LINKED ISSUE #115: Make LLM to output test cases specification (docstring)

### PR DESCRIPTION
**Pull request by JohnShiuMK**
fyi, I have renamed `analyze.py` to `evaluate.py`

close #115

### CODE REVIEW

**Comment by SoloSynth1** [comment]
@JohnShiuMK Is this based on the development branch for #104? I'm seeing some similar changes. In this case, I'm thinking let's put our effort in closing #104 first. Would that sound good to you?

**Comment by JohnShiuMK** [comment]
> @JohnShiuMK Is this based on the development branch for #104? I'm seeing some similar changes. In this case, I'm thinking let's put our effort in closing #104 first. Would that sound good to you?

yes, let me review #104 tmr. 
I think the similar change is because this 116 is built based on the development branch for 104. The main contribution of this 116 is just the `src/test_creation/generate.py`

**Comment by SoloSynth1** [comment]
> > @JohnShiuMK Is this based on the development branch for #104? I'm seeing some similar changes. In this case, I'm thinking let's put our effort in closing #104 first. Would that sound good to you?
> 
> 
> 
> yes, let me review #104 tmr. 
> 
> I think the similar change is because this 116 is built based on the development branch for 104. The main contribution of this 116 is just the `src/test_creation/generate.py`

Thanks, I have already merged #107 into this branch

**Comment by SoloSynth1** [comment]
@JohnShiuMK I have finished working on this branch. 

Since this branch is based off from #107, the "Files changed" tab is not very useful in showing the differences made. I think you can follow [this link](https://github.com/UBC-MDS/test-creation/compare/104-add-line-number...115-dev-test-spec-generator) to see the comparison between these two branches.

**Comment by JohnShiuMK** [comment]
Hi @SoloSynth1, I'm okay with this PR now.
Please feel free to approve and merge. (As I'm the owner of this PR)

**Review by SoloSynth1 — APPROVED** [review]
LGTM. Thanks @JohnShiuMK for the PR!

**Pull request merged**
