### PR TITLE
feat: Wrap the system into package

### LINKED ISSUE #111: Wrap the system into package

### LINKED ISSUE #120: Write basic tests for the system

### LINKED ISSUE #121: (Optional) Question: Do we have to keep it as CLI tool or API?

### PR DESCRIPTION
**Pull request by SoloSynth1**
This PR:
- wraps the existing codes as a Python package
- moves Python dependencies to be controlled by `poetry`
- add `pytest` as dev dependencies
- writes draft tests for `Checklist` as basic tests and examples for further test suite development
- adds CI checks to be triggered in Github Actions on PR creations and pushs
- moves existing scripts out of the project root to `scripts/`
- creates an executable `test-creation` that acts as basis for future CLI tool's entry point
- update `README.md` for latest instruction on how to install and run the project codes

Closes #111, closes #120, closes #121.

### CODE REVIEW

**Comment by JohnShiuMK** [comment]
@SoloSynth1, encountered this when I did `pytest tests/`, is it expected?
Screenshot 2024-06-03 at 12 10 31 AM

**Comment by SoloSynth1** [comment]
> @SoloSynth1, encountered this when I did `pytest tests/`, is it expected?
> 
> Screenshot 2024-06-03 at 12 10 31 AM
> 
> 

Fixed in latest commit

**Comment by JohnShiuMK** [comment]
Now, it's like this:
Screenshot 2024-06-03 at 4 24 29 PM

I tried re-install the conda env and follow the installation guide in the README...
Am I missing something?

**Comment by JohnShiuMK** [comment]
Fixed. Also, the argument `checklist_format` is no longer needed in the Checklist, so I have removed them from the tests/test_creation.py
Screenshot 2024-06-03 at 4 39 34 PM

**Review by JohnShiuMK — APPROVED** [review]
looks good to me for now

**Pull request merged**
