### PR TITLE
133 generate response raw data

### PR DESCRIPTION
**Pull request by JohnShiuMK**
To run on [Openja](https://arxiv.org/pdf/2312.12604)'s 11 repos, 30 times for each, and save responses into pickles

### CODE REVIEW

**Comment by SoloSynth1** [comment]
@JohnShiuMK With the inclusion of class objects in `EvaluationResponse`, it seems like in `Repository._get_file_function_lineno_map()` the use of `lambda` is causing pickle to fail:

```
Traceback (most recent call last):
  File "/Users/solosynth1/anaconda3/envs/test-creation/bin/test-creation", line 6, in <module>
    sys.exit(cli_main())
             ^^^^^^^^^^
  File "/Users/solosynth1/workspace/ubc-mds/capstone/test-creation/src/test_creation/cli/main.py", line 25, in main
    fire.Fire(TestCreation)
  File "/Users/solosynth1/anaconda3/envs/test-creation/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/solosynth1/anaconda3/envs/test-creation/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/solosynth1/anaconda3/envs/test-creation/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/solosynth1/workspace/ubc-mds/capstone/test-creation/src/test_creation/cli/repository.py", line 76, in evaluate
    pickle.dump(response, file)
AttributeError: Can't pickle local object 'Repository._get_file_function_lineno_map.<locals>.<lambda>'
```

I have commented the lines responsible for creating the pickle, and output json instead.

**Comment by SoloSynth1** [comment]
@JohnShiuMK The branch is ready to be reviewed.

**Comment by JohnShiuMK** [comment]
@SoloSynth1, duplicated `-r` for `REPO_PATH` and `render_report_to`. So `-r` doesn't work (I had to use `--render_report_to`)

Another suggestion for a naming: I think `save_response_to` may be better than `save_to`, what do you think? 

Screenshot 2024-06-11 at 9 45 38 AM
Screenshot 2024-06-11 at 9 45 57 AM


But these are small things, I'm gonna merge it for now

**Review by SoloSynth1 — APPROVED** [review]
Changed some flags' name so now there is no ambiguous short forms. LGTM.

**Pull request merged**
