### PR TITLE
 Add human_evaluation_report-qlib.md

### PR DESCRIPTION
**Pull request by tonyshumlh**
Hi @jinyz8888 . 
I have consolidated the evaluation report on  Repo `qlib` 
Please kindly review and edit if necessary.

### CODE REVIEW

**Review by JohnShiuMK — CHANGES_REQUESTED** [review]
It would be good to keep a link to your communication record at the bottom of the md, as the following:
Screenshot 2024-06-06 at 12 08 48 PM

I helped add it to the `lightfm`'s last time
https://github.com/UBC-MDS/test-creation/blob/main/report/repo_human_evaluation/human_evaluation_report-lightfm.md

**Comment by tonyshumlh** [comment]
> It would be good to keep a link to your communication record at the bottom of the md, as the following: Screenshot 2024-06-06 at 12 08 48 PM
> 
> I helped add it to the `lightfm`'s last time https://github.com/UBC-MDS/test-creation/blob/main/report/repo_human_evaluation/human_evaluation_report-lightfm.md

Added the communication record

**Comment by jinyz8888** [comment]
@tonyshumlh I made a minor change, please check it :)

**Review by jinyz8888 — COMMENTED** [review]
@tonyshumlh I made a minor change. Please check it. Thanks.

**Comment by tonyshumlh** [comment]
Thanks for fixing it. Looks good to me

**Review by JohnShiuMK — APPROVED** [review]
good jobs, thanks!

**Pull request merged**
