### PR TITLE
Proposal fine tune

### PR DESCRIPTION
**Pull request by tonyshumlh**
Screenshot 2024-05-07 at 6 17 57 PM

### CODE REVIEW

**Review by SoloSynth1 — COMMENTED** [review]
@tonyshumlh I think Simon mentioned we should add caption to the figure. On top of that, I'm also adding a short passage about the checklist to be delivered.

**Comment by SoloSynth1** [comment]
@tonyshumlh I finished adding the checklist-related description, example, and also references. Please take a look, thanks!

**Comment by tonyshumlh** [comment]
@SoloSynth1 The added part looks good to me. Just 1 thing that the proposal seems now slightly more than 1200 word limits
Screenshot 2024-05-08 at 11 54 22 PM
Screenshot 2024-05-08 at 11 54 27 PM

**Review by SoloSynth1 — APPROVED** [review]
LGTM, thanks @tonyshumlh for the input

**Comment by SoloSynth1** [comment]
Merging into `main`.

**Pull request merged**
